sudo: false
language: node_js
node_js:
- 10
cache: npm
branches:
  only:
  - master # build master branch only

env:
  global:
  - GIT_USER: aron-xx
  #- HEXO_BACKUP_REPO: github.com/aron-xx/hexo-backup.git
  - HEXO_THEME_REPO: github.com/aron-xx/hexo-theme-matery-master.git
  - GITHUB_PAGES_REPO: github.com/aron-xx/aron-xx.github.io.git
  - VOIDKING_REPO: github.com/aron-xx/aron-xx.git

before_install:
- export TZ='Asia/Shanghai'
- npm install hexo -g
- npm install gulp-cli -g

install:
- npm install

script:
- git clone https://${HEXO_THEME_REPO} themes/hexo-theme-matery-master
#- git clone https://${GIT_USER}:${GITHUB_TOKEN}@${HEXO_BACKUP_REPO} hexo-backup
- mv hexo-backup/source .
- rm -rf source/private
- npm run build

after_success:
- git config --global user.name "kiki"
- git config --global user.email "1412730765@qq.com"
- git clone https://${GIT_USER}:${GITHUB_TOKEN}@${GITHUB_PAGES_REPO} aron-xx
- unalias cp
- cp -rf public/. aron-xx
- cd aron-xx
- git add .
- git commit -m "Travis CI Auto Builder"
- git push --force --quiet "https://${GIT_USER}:${GITHUB_TOKEN}@${GITHUB_PAGES_REPO}" master:master